[05/12/23  06:56:10] [  78]  XI Server Manager v1.0 --- Started
[05/12/23  06:56:11] [Auto_Start  83]  AutoStart: XI Servers
[05/12/23  06:56:11] [StartServer  466]  Atempting to start: xi_map.exe
[05/12/23  06:56:12] [StartServer  481]  Started Server: xi_map.exe
[05/12/23  06:56:12] [StartServer  482]  Process Name: xi_map.exe --- Process PID: 1956 --- HwndID: 786624
[05/12/23  06:56:12] [StartServer  483]  Process Path: C:\Users\FFXI\AppData\Local\Programs\Python\Python311\server\xi_map.exe
[05/12/23  06:56:12] [StartServer  486]  Docking Server: xi_map.exe to main Window
[05/12/23  06:56:12] [ServerTimer  99]  Server Check Timer Started
[05/12/23  06:56:12] [    ]   
[05/12/23  06:56:12] [StartServer  466]  Atempting to start: xi_world.exe
[05/12/23  06:56:13] [StartServer  481]  Started Server: xi_world.exe
[05/12/23  06:56:13] [StartServer  482]  Process Name: xi_world.exe --- Process PID: 3712 --- HwndID: 524870
[05/12/23  06:56:13] [StartServer  483]  Process Path: C:\Users\FFXI\AppData\Local\Programs\Python\Python311\server\xi_world.exe
[05/12/23  06:56:13] [StartServer  486]  Docking Server: xi_world.exe to main Window
[05/12/23  06:56:13] [ServerTimer  99]  Server Check Timer Started
[05/12/23  06:56:13] [    ]   
[05/12/23  06:56:14] [StartServer  466]  Atempting to start: xi_search.exe
[05/12/23  06:56:14] [StartServer  481]  Started Server: xi_search.exe
[05/12/23  06:56:14] [StartServer  482]  Process Name: xi_search.exe --- Process PID: 7820 --- HwndID: 197772
[05/12/23  06:56:14] [StartServer  483]  Process Path: C:\Users\FFXI\AppData\Local\Programs\Python\Python311\server\xi_search.exe
[05/12/23  06:56:14] [StartServer  486]  Docking Server: xi_search.exe to main Window
[05/12/23  06:56:14] [ServerTimer  99]  Server Check Timer Started
[05/12/23  06:56:14] [    ]   
[05/12/23  06:56:15] [StartServer  466]  Atempting to start: xi_connect.exe
[05/12/23  06:56:15] [StartServer  481]  Started Server: xi_connect.exe
[05/12/23  06:56:15] [StartServer  482]  Process Name: xi_connect.exe --- Process PID: 6908 --- HwndID: 655414
[05/12/23  06:56:15] [StartServer  483]  Process Path: C:\Users\FFXI\AppData\Local\Programs\Python\Python311\server\xi_connect.exe
[05/12/23  06:56:15] [StartServer  486]  Docking Server: xi_connect.exe to main Window
[05/12/23  06:56:15] [ServerTimer  99]  Server Check Timer Started
[05/12/23  06:56:15] [    ]   
[05/12/23  06:56:17] [Auto_Start  90]  AutoStart: pydarkstar broker
[05/12/23  06:56:17] [StartServer  466]  Atempting to start: pydarkstar_broker.exe
[05/12/23  06:56:17] [StartServer  481]  Started Server: pydarkstar_broker.exe
[05/12/23  06:56:17] [StartServer  482]  Process Name: cmd.exe --- Process PID: 7620 --- HwndID: 3474504
[05/12/23  06:56:17] [StartServer  483]  Process Path: C:\Windows\System32\cmd.exe
[05/12/23  06:56:17] [StartServer  486]  Docking Server: pydarkstar_broker.exe to main Window
[05/12/23  06:56:17] [ServerTimer  99]  Server Check Timer Started
[05/12/23  06:56:17] [    ]   
[05/12/23  06:57:17] [ServerCheck  411]  Starting Server Checks: 
[05/12/23  06:57:17] [ServerCheck  412]  xi_map status: 1
[05/12/23  06:57:17] [ServerCheck  413]  xi_world status: 1
[05/12/23  06:57:17] [ServerCheck  414]  xi_search status: 1
[05/12/23  06:57:17] [ServerCheck  415]  xi_connect status: 1
[05/12/23  06:57:17] [ServerCheck  416]  pydarkstar broker status: 1
[05/12/23  06:57:20] [Shutdown_All_Servers  382]  Shutting down all servers and exiting XI Server Manager
